on:
  push:
    branches:
      - test-sync

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    steps:
      - name: openfn deploy
        uses: midigofrank/cli-deploy-action@v0.1.12
        with:
          secret_input: ${{ secrets.OPENFN_b10fa8d1_1309_4c70_ae4e_f4fa0cfcbed5_API_KEY }}
          config_path_input: 'openfn-b10fa8d1-1309-4c70-ae4e-f4fa0cfcbed5-config.json'
