on:
  push:
    branches:
      - main

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_0bf6c2ac_1894_433b_b576_5a0b50ec27da_API_KEY }}
          config_path_input: 'openfn-4adf2644-ed4e-4f97-a24c-ab35b3cb1efa-config.json'
